### ISSUE TITLE
インスタンスの停止の後再起動の手順となっている

### ISSUE THREAD

**Issue by matyuda** [shigeru-oda/zenn#1]
https://zenn.dev/shigeru_oda/books/521fa5a5a9c558c6275d/viewer/setup-cloud9#%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E3%81%AE%E5%81%9C%E6%AD%A2

インスタンスの停止→EBSの拡張→インスタンスの再起動
の手順ですが
インスタンスの停止→EBSの拡張→インスタンスの起動
もしくは
EBSの拡張→インスタンスの再起動
としていただいた方が良いと思います。

私は後者で試したところ拡張できていることを確認できました。

**Comment by matyuda** [comment]
インスタンスの停止をすると勝手に起動しちゃいますね。。。

**Comment by shigeru-oda** [comment]
BSの拡張→インスタンスの再起動に切り替えました。

**Comment by matyuda** [comment]
ありがとうございます。
変更いただいた手順にて拡張できることを確認できました。
