### ISSUE TITLE
ap-northeast-2でデプロイに失敗する

### ISSUE THREAD

**Issue by matyuda** [shigeru-oda/zenn#2]
<img width="1393" alt="スクリーンショット 2022-03-02 20 08 45" src="https://user-images.githubusercontent.com/24763623/156351097-dcf24dfa-26d6-4468-b302-dbedeac0955d.png">

**Comment by shigeru-oda** [comment]
使うリージョンは東京とバージニア北部　慣れている方はバージニア北部でお願いします。　ってしておきます。

**Comment by shigeru-oda** [comment]
以下で記載。

# リージョン
以下、どちらかのリージョンをご利用ください。
慣れている方はバージニア北部に寄って頂けると負荷分散としてありがたいです。
- 東京リージョン(ap-northeast-1)
- バージニア北部(us-east-1)
